export const API_ROUTES = {
  user: {
    login: '/user/login',
    register: '/user/register',
    logout: '/user/logout',
  },
  transactionLogs: {
    list: '/transaction-logs/list-transactions',
    update: (id: string) => `/transaction-logs/update/${id}`,
    sync: '/transaction-logs/sync-transactions',
    labels: '/transaction-logs/list-labels',
    addCashMemo: '/transaction-logs/add-cashmemo',
    uploadFile: '/transaction-logs/upload-data-from-file',
    parsePdf: '/transaction-logs/parse-pdf',
    checkDuplicates: '/transaction-logs/check-duplicates',
  },
  transactionGroups: {
    list: '/transaction-groups',
    listLocal: '/transaction-groups/list',
    create: '/transaction-groups',
    detail: (id: string) => `/transaction-groups/${id}`,
    add: (id: string) => `/transaction-groups/${id}/add`,
    remove: (id: string) => `/transaction-groups/${id}/remove`,
    dissolve: (id: string) => `/transaction-groups/${id}`,
    sync: '/transaction-groups/sync',
  },
  debt: {
    list: '/debt/list-debts',
    create: '/debt/add-debt',
    update: '/debt/update-debt',
    delete: (id: string) => `/debt/delete-debt/${id}`,
    get: (id: string) => `/debt/get-debt/${id}`,
    recordPayment: '/debt/record-payment',
    paymentHistory: (id: string) => `/debt/payment-history/${id}`,
    payoffProjection: (id: string) => `/debt/payoff-projection/${id}`,
    summary: '/debt/summary',
    strategy: '/debt/strategy',
  },
  goals: {
    list: '/goals',
    create: '/goals',
    update: (id: string) => `/goals/${id}`,
    delete: (id: string) => `/goals/${id}`,
    contributions: '/goals/contributions',
  },
  ai: {
    chat: '/ai/chat',
    chatHistory: '/ai/chat-history',
    clearChatHistory: (sessionId?: string) => `/ai/chat-history${sessionId ? `/${sessionId}` : ''}`,
    annotate: '/ai/annotate',
    suggestCategories: '/ai/suggest-categories',
    applySuggestions: '/ai/apply-suggestions',
    rejectSuggestions: '/ai/reject-suggestions',
    debtStrategy: '/ai/debt-strategy',
    budgetRecommendations: '/ai/budget-recommendations',
  },
} as const
