export const API_ROUTES = {
  user: {
    login: '/user/login',
    register: '/user/register',
    logout: '/user/logout',
  },
  transactionLogs: {
    list: '/transaction-logs/list-transactions',
    update: (id: string) => `/transaction-logs/update/${id}`,
    sync: '/transaction-logs/sync-transactions',
    labels: '/transaction-logs/list-labels',
    addCashMemo: '/transaction-logs/add-cashmemo',
    uploadFile: '/transaction-logs/upload-data-from-file',
    parsePdf: '/transaction-logs/parse-pdf',
    checkDuplicates: '/transaction-logs/check-duplicates',
  },
  transactionGroups: {
    list: '/transaction-groups',
    listLocal: '/transaction-groups/list',
    create: '/transaction-groups',
    detail: (id: string) => `/transaction-groups/${id}`,
    add: (id: string) => `/transaction-groups/${id}/add`,
    remove: (id: string) => `/transaction-groups/${id}/remove`,
    dissolve: (id: string) => `/transaction-groups/${id}`,
    sync: '/transaction-groups/sync',
  },
  debt: {
    list: '/debt',
    create: '/debt',
    update: (id: string) => `/debt/${id}`,
    delete: (id: string) => `/debt/${id}`,
    emiPayments: '/debt/emi-payments',
  },
  goals: {
    list: '/goals',
    create: '/goals',
    update: (id: string) => `/goals/${id}`,
    delete: (id: string) => `/goals/${id}`,
    contributions: '/goals/contributions',
  },
  ai: {
    chat: '/ai/chat',
    chatHistory: '/ai/chat-history',
    clearChatHistory: (sessionId?: string) => `/ai/chat-history${sessionId ? `/${sessionId}` : ''}`,
    annotate: '/ai/annotate',
    suggestCategories: '/ai/suggest-categories',
    categorizationJobStatus: (jobId: string) => `/ai/suggest-categories/status/${jobId}`,
    applySuggestions: '/ai/apply-suggestions',
    rejectSuggestions: '/ai/reject-suggestions',
    debtStrategy: '/ai/debt-strategy',
    budgetRecommendations: '/ai/budget-recommendations',
  },
  ledgers: {
    list: '/ledgers',
    create: '/ledgers',
    detail: (id: string) => `/ledgers/${id}`,
    update: (id: string) => `/ledgers/${id}`,
    delete: (id: string) => `/ledgers/${id}`,
    addEntry: (id: string) => `/ledgers/${id}/entries`,
    removeEntry: (id: string, entryId: string) => `/ledgers/${id}/entries/${entryId}`,
    linkTransaction: (id: string) => `/ledgers/${id}/link-transaction`,
    settle: (id: string) => `/ledgers/${id}/settle`,
    sync: '/ledgers/sync',
  },
} as const
