export { DebtsPage } from './pages/Debts'
export { DebtTable } from './components/Debt'
export { EMIPaymentModal } from './components/EMIPaymentModal'
export type { IDebt, IEMIPayment, DebtStatus } from './types/debt'
export { calculateEMI, calculateTotalInterest, projectedPayoffDate } from './utils/debtUtils'
