export { GoalsPage } from './pages/Goals'
export { Goals as GoalsComponent } from './components/Goals'
export { ContributionModal } from './components/ContributionModal'
export type { IGoal, IGoalContribution } from './types/goal'
export { applyContribution } from './utils/goalUtils'
